spring.application.name=scheduling-service

spring.datasource.url=jdbc:postgresql://localhost:5432/doodle_scheduling
spring.datasource.username=doodle_user
spring.datasource.password=doodle_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

info.app.name=Doodle Scheduling API
info.app.version=1.0.0
info.app.description=Doodle coding challenge